const LIST = {
  REQUEST: "PIZZAS_LIST_REQUEST",
  SUCCESS: "PIZZAS_LIST_SUCCESS",
  ERROR: "PIZZAS_LIST_ERROR",
  RESET: "PIZZAS_LIST_RESET",
};

const ADD = {
  REQUEST: "PIZZAS_ADD_REQUEST",
  SUCCESS: "PIZZAS_ADD_SUCCESS",
  ERROR: "PIZZAS_ADD_ERROR",
  RESET: "PIZZAS_ADD_RESET",
};

const DELETE = {
  REQUEST: "PIZZAS_DELETE_REQUEST",
  SUCCESS: "PIZZAS_DELETE_SUCCESS",
  ERROR: "PIZZAS_DELETE_ERROR",
  RESET: "PIZZAS_DELETE_RESET",
};

const DETAILS = {
  REQUEST: "PIZZAS_DETAILS_REQUEST",
  SUCCESS: "PIZZAS_DETAILS_SUCCESS",
  ERROR: "PIZZAS_DETAILS_ERROR",
  RESET: "PIZZAS_DETAILS_RESET",
};

const EDIT = {
  REQUEST: "PIZZAS_EDIT_REQUEST",
  SUCCESS: "PIZZAS_EDIT_SUCCESS",
  ERROR: "PIZZAS_EDIT_ERROR",
  RESET: "PIZZAS_EDIT_RESET",
};

export const PizzaActionTypes = {
  PIZZAS_LIST: LIST,
  ADD: ADD,
  DELETE: DELETE,
  DETAILS: DETAILS,
  EDIT: EDIT,
};
