const CREATE = {
  REQUEST: "USER_REGISTER_REQUEST",
  SUCCESS: "USER_REGISTER_SUCCESS",
  ERROR: "USER_REGISTER_ERROR",
  RESET: "USER_REGISTER_RESET",
};

export const UserActionTypes = {
  REGISTER: CREATE,
};
